service: spend-legalizer

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: legalize
          method: post
          cors: true
      - http:
          path: legalize
          method: get
          cors: true